### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'run_command'

### ISSUE THREAD

**Issue by binarykitchen** [victorporof/Sublime-JSHint#110]
```
Exception in thread Thread-584:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 1142, in run
  File "/home/xxx/.config/sublime-text-3/Packages/JSHint Gutter/JSHint.py", line 188, in <lambda>
    self.timer = Timer(timeout, lambda: view.window().run_command("jshint", { "show_panel": False }))
AttributeError: 'NoneType' object has no attribute 'run_command'
```

**Comment by binarykitchen** [comment]
Hello? This is still happening ...

**Comment by victorporof** [comment]
Can't find a solution to this without proper STR. Are there any specific conditions in which this is happening?

**Comment by binarykitchen** [comment]
Honestly, no idea. Just reporting here.

**Comment by skarfacegc** [comment]
I'm getting the same error (on OSX)  not sure why/when it happens. jshint gutter seems to be working fine.

**Comment by victorporof** [comment]
Just found out that this sometimes happens when running sublime from your CLI. Couldn't get reliable steps to reproduce though...
